services:
  banco:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db_tarefas_dio
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=RootRoot98*
    ports:
      - 1433:1433
